### ISSUE TITLE
Amend pathway for Month 3 scan patients to be follow-up at Month 24

### ISSUE THREAD

**Issue by ASW-Analyst** [NHS-Transformation-Unit/Lung_Health_Checks#19]
The LHC pathway has been updated to reflect that there is a cohort of patients who will be seen for their 3-month scan and then require follow-up at 24 months. This additional flow in the pathway will need to be modelled. This will require:

- [x]  **Creating a version 5 of the excel `config_inputs_v5.xlsx` file.** Within the `m3_treat` tab an additional assumption `m3_m24_fu_rate` will need to be added to capture the percentage of patients with a positive CT scan who are referred for a follow-up scan at 24 months.
- [x] **Amending the load range of the `assumptions_m3_treat`.** Within the `load_inputs_config.R` file the [`range`](https://github.com/NHS-Transformation-Unit/Lung_Health_Checks/blob/c061e2e774f4fb1b99abb950db83d86b89da2d80/src/load/load_inputs_config.R#L14) argument of the `read_excel` call for `assumptions_m3_treat` will need amending to include the new assumption.
- [x] **Amending the `m3_treat_groups` function.** Within the [`m3_treatment.R`](https://github.com/NHS-Transformation-Unit/Lung_Health_Checks/blob/c061e2e774f4fb1b99abb950db83d86b89da2d80/src/model/functions/m3_treatment.R#L1) file the following amendments will need to be made to include the new assumption:
     - [x] Add an argument to the function definition
     - [x] Add an additional line in the [`case_when`](https://github.com/NHS-Transformation-Unit/Lung_Health_Checks/blob/c061e2e774f4fb1b99abb950db83d86b89da2d80/src/model/functions/m3_treatment.R#L26) to randomise to a follow-up scan at 24 months.
     - [x] Create the `m3_treat_24m_fu_df`
     - [x] Add `m3_treat_24m_fu_df` to the function [return](https://github.com/NHS-Transformation-Unit/Lung_Health_Checks/blob/c061e2e774f4fb1b99abb950db83d86b89da2d80/src/model/functions/m3_treatment.R#L62)
- [x] **Amend the `m3_treat_groups` function call in the y1, y2, y3, y4 and y5 files.** For each year of the model the `yX_m3_treat.R` files will need the following amendments:
     - [x] Amend the function call for `yX_m3_treat_groups_list` definition to include the `m3_m24_fu_rate` argument (here for [y1](https://github.com/NHS-Transformation-Unit/Lung_Health_Checks/blob/c061e2e774f4fb1b99abb950db83d86b89da2d80/src/model/y1/y1_6_m3_treat.R#L4))
     - [x] Create `yX_m3_m24_FU_input_df`. This will be the cohort of patients modelled to follow-up at 24 months. Will then be added to the input dataframe for the Month 24 modelling.
 - [x] **Append month this cohort of patients to the Month 24 input dataframe.** The `yX_m24_FU_input_df` contains the patients who have a 24 month scan and then need to be randomised to an outcome. This will now need to include the patients in `yX_m3_m24_FU_input_df`. Appending this in the `yX_8_m12_treat.R` to the `yX_m12_treat_groups_list[[4]]` is required. Link to [y1](https://github.com/NHS-Transformation-Unit/Lung_Health_Checks/blob/c061e2e774f4fb1b99abb950db83d86b89da2d80/src/model/y1/y1_8_m12_treat.R#L28) for example.
 - [x] **Amend formatting of Month 3 CT Outcome Tables and Charts**. The [`yX_visuals.R`](https://github.com/NHS-Transformation-Unit/Lung_Health_Checks/blob/c061e2e774f4fb1b99abb950db83d86b89da2d80/src/visualisation/y1_visuals.R#L124) script needs a `case_when` amending for the tidying of the 24-month follow-up outcome. Also needs amending in the equivalent [`yX_tables.R`](https://github.com/NHS-Transformation-Unit/Lung_Health_Checks/blob/c061e2e774f4fb1b99abb950db83d86b89da2d80/src/visualisation/tables/y1_tables.R#L507) file. Complete this for the other model years.
 - [x] **Test model run to ensure that results are consistent with expectations.**

**Comment by elliotroyle** [comment]
Please see PR included above for update on progress.

**Comment by elliotroyle** [comment]
All changes have been made and are ready for review. I've ran the model as well and things seem to be formatted correctly. Please let me know if there are any further changes needed.
