### ISSUE TITLE
Update Project Documentation

### ISSUE THREAD

**Issue by ASW-Analyst** [NHS-Transformation-Unit/Lung_Health_Checks#21]
Following the amendments from #19 and #20 review all documentation to ensure that any changes are recorded. Add the new pathway map to the [`README.md`](https://github.com/NHS-Transformation-Unit/Lung_Health_Checks/blob/main/README.md)

**Comment by elliotroyle** [comment]
Pathway model included in merge #24.

**Comment by elliotroyle** [comment]
No other files appear to require changes.
